# CCM Tutorial, Lecture II

In this lecture, we will explore how to control workflow in a code using conditionals and loops. For more information, we recommend reviewing some of the online documentation available at https://docs.python.org/2/tutorial/controlflow.html. We will also see how to make code more modular by creating user defined functions. 

## Conditionals & Comparisons in Python
    
### Conditionals in Python    
0. In Python, there are no "case" or "switch" options that are available in other languages, but we can get the same functionality by using dictionary mappings. However, this is beyond the scope of this tutorial. 
1. You will find that most things can be done using the if/elif/else syntax:
```
if condition:
    #do stuff
elif condition:
    #do stuff
else:
    #do stuff
```       

***All parts of the conditional are indented.*** Unlike other languages that use terms like "end" or "end if" (or perhaps make use of brackets like "{ }") to signify the block of code corresponding to an if-elseif-else, Python interprets everything in terms of indenting. This is also true in for-loops as we will see below.
       
### Comparison operators  (*LET a=3, b=5*)
==:	If the values of two operands are equal, then the condition becomes true.	*(a == b) is not true.*

!=:	If values of two operands are not equal, then condition becomes true.  *(a != b) is true.* (Alternatively, one could use `<>` in place of `!=`, but this is not very common.)

 ">":	If the value of left operand is greater than the value of right operand, then condition becomes true.	*(a > b) is not true.*

"<": If the value of left operand is less than the value of right operand, then condition becomes true.	*(a < b) is true.*

">=":	If the value of left operand is greater than or equal to the value of right operand, then condition becomes true.	*(a >= b) is not true.*

"<=":	If the value of left operand is less than or equal to the value of right operand, then condition becomes true.	*(a <= b) is true.*

We can us **and** and **or** to combine sets of comparison operators and **not** to negate a statement. 

Try changing different values of `x` in the code snippets below and see what happens.

In [17]:
import numpy as np
x = -1
if x >= 0 and not(x == 2 or x == 3):
    f = np.power(x,.5)/((x-2.0)*(x-3.0))
    print f
elif x < 0:
    print 'Square root of negative number'
    f = np.nan
elif x == 2.0:
    print 'Division by zero with different limits'
    f = np.nan

Square root of negative number


In [18]:
# if x > 1 or x < -1 f(x)=0
# elif x<= 0 f(x)=1+x
# else f(x)=1-x

x=-.25
if x> 1 or x< -1:
    f=0.0
elif x<=0:
    f=1.0+x
else: 
    f=1.0-x
print f

0.75


## Functions in Python 
In the code snippets above, a value of `x` serves as the input into a conditional statement that determines what output value `f` should be assigned based on the value of `x`. If we wish to use this functionality many times in the code, we would probably like to avoid writing the if/elif/else structure at each point where it is to be used for a variety of reasons including, but not limited to, the following:
- If we ever decide to change how `f` is computed, then we would have to find/replace every instance of it within the code.
- Even the most terse scientific code can easily become hundreds if not thousands of lines long, and we want to avoid making the code more difficult to read, use, and debug than is absolutely necessary. 

This motivates the development of user-defined functions in Python. The basic syntax is shown below.

```
def functionname( parameters ):
   """function_docstring"""
   function_suite
   return [expression]
```
### A brief discussion on docstrings and commenting in code
The (triple) quotes is where you put in a documentation string for your function.  It is entirely optional, but it is always a good idea to document your code even when it is entirely in the developmental/testing phase. There are some best practices that you can read about at https://docs.python.org/devguide/documenting.html or http://docs.python-guide.org/en/latest/writing/documentation/. 

Good tools such as Sphinx http://www.sphinx-doc.org/en/1.4.8/ can turn properly documented code into easy to read/navigate html files to help expand the community of users for any code you develop. For example, see http://ut-chg.github.io/BET/ where Sphinx was used to generate the documentation. 

### parameters and keyword arguments in a function
Notice that in the definition of the function, there is a `parameters` variable, which is often a list of parameters (as shown below). These are normally ordered **UNLESS** you supplement them with *keyword args* in the function call (i.e., when you actually use the function you may specify which argument corresponds to which parameter).  The next two code snippet illustrates this.

In [6]:
def myfun(x,y):
    if x<y:
        z = x+2*y
    else:
        z= x-2*y
    return z

print myfun(2,3)
print myfun(2.0,3.0)
print myfun(3.0,2.0) #switching order of inputs

print myfun(x=2,y=3.0) #keyword argument
print myfun(y=3.0,x=2.0) #switching the order of inputs of keyword arguments does nothing

# Above, try printing myfun(x=2,3.0). 
# The take home message? Once you commit to using keywords in a function call, then you better be all in.

print myfun('silly ','test')    

8
8.0
-1.0
8.0
8.0
silly testtest


Obviously Python does not use type-checking for functions, but it allows useful types of polymorphism.

Python also allows to set defaults within the parameter list of a function call.  Let's tweak myfun a little.

Defaults need to **come after** functions parameters with non-default values.

In [25]:
def myfun2(x=1,y=2):
    if x<y:
        z = x+2*y
    else:
        z= x-2*y
    return z

print myfun2()
print myfun2(1.0)
print myfun2(y=3)

5
5.0
7


**We can even pass a function to another function!**

In [30]:
print myfun(myfun2(),myfun2(y=3))

19


### Python is pass by reference OR pass by value

####  *Pass by reference*
This means Python passes the reference to the variable, not just the value.  This can cause some different behavior when certain *in place* operators are used.  Classes, numpy arrays, etc. are passed by reference.

#### *Pass by value* 
This means Python passes the value and creates a new copy within the function. Variables that are strings, floats, and ints are passed by value (*they are immutable data types* meaning that the value is left unchanged by the function).

Python variables created within a function also have local *scope*.

In [55]:
import numpy as np
def tester(var):
    var *= 2      #if var is mutable, replaces in place (pass-by-reference)
    print 'within tester, the passed variable is changed to \n var = ', var
    a = 3
    print 'tester changed a in the scope of the function to', a
    return

a=2
print 'before tester, a = ', a
tester(a)
print 'after tester, a = ', a
A=np.ones([2,2])
print 'before tester, \n A = ', A
tester(A)
print 'after tester, \n A = ', A
tester(A)
print 'after tester(2*A), \n A = ', A


before tester, a =  2
within tester, the passed variable is changed to 
 var =  4
tester changed a in the scope of the function to 3
after tester, a =  2
before tester, 
 A =  [[ 1.  1.]
 [ 1.  1.]]
within tester, the passed variable is changed to 
 var =  [[ 2.  2.]
 [ 2.  2.]]
tester changed a in the scope of the function to 3
after tester, 
 A =  [[ 2.  2.]
 [ 2.  2.]]
within tester, the passed variable is changed to 
 var =  [[ 4.  4.]
 [ 4.  4.]]
tester changed a in the scope of the function to 3
after tester(2*A), 
 A =  [[ 4.  4.]
 [ 4.  4.]]


### Wait a minute...

What if I want to do local work to a *mutable* data type (i.e. a numpy array) but not have the change reflected back after function exit?  

The answer is to not use *in place* operators like +=, \*=, etc.  `var = var*2` creates a local copy of var and adds 2 to every entry.

In [58]:
def tester2(var):
    var = var*2    #if mutable, creates local copy of var.
    print 'within tester2, the passed variable is changed to, \n input = ',var
    return 

A=np.eye(3) # creates 3x3 array with a_ii = 1, 0 otherwise.
print 'before tester2,\n A = ', A
tester2(A)
print 'after tester2,\n A = ', A

before tester2,
 A =  [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
within tester2, the passed variable is changed to, 
 input =  [[ 2.  0.  0.]
 [ 0.  2.  0.]
 [ 0.  0.  2.]]
after tester2,
 A =  [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## Looping in Python

### For loops

**Syntax** 
```
for iterator in list:
    #indent for the loop
    #do cool stuff in the loop
#noindent to close the loop'
```
The list can be strings, for example:
```
for string in ('Alpha','Romeo','Sailor','Foxtrot'):
    #string takes on values 'Alpha', 'Romeo', etc. in order.
    print string
```
    

You will commonly use the ``xrange`` command to build lists of numbers for iterating (see https://docs.python.org/2/library/functions.html#xrange).
This is better than ``range`` for long sets of numbers or if you break the loop earlier.

**SYNTAX** 
```
xrange(stop)  #assumes start=0
xrange(start, stop[, step])
```

Note that it **DOES NOT** execute the stop value.

Let's  sum the first 20 terms of the geometric series corresponding to $2^{-x}$

In [9]:
sum=0
for n in xrange(20):   #identical so xrange(0,20) or xrange(0,20,1)
    sum += 2**(-n)
    print n, 'Sum = ', sum
    
print 'Now start subtracting from the sum'
    
for n in xrange(19,-1,-1): #you need the colon
    sum -= 2**(-n)  #all the things at the level of the loop get one indent
    print n, 'Sum = ', sum #done with the loop variable

0 Sum =  1
1 Sum =  1.5
2 Sum =  1.75
3 Sum =  1.875
4 Sum =  1.9375
5 Sum =  1.96875
6 Sum =  1.984375
7 Sum =  1.9921875
8 Sum =  1.99609375
9 Sum =  1.998046875
10 Sum =  1.9990234375
11 Sum =  1.99951171875
12 Sum =  1.99975585938
13 Sum =  1.99987792969
14 Sum =  1.99993896484
15 Sum =  1.99996948242
16 Sum =  1.99998474121
17 Sum =  1.99999237061
18 Sum =  1.9999961853
19 Sum =  1.99999809265
Now start subtracting from the sum
19 Sum =  1.9999961853
18 Sum =  1.99999237061
17 Sum =  1.99998474121
16 Sum =  1.99996948242
15 Sum =  1.99993896484
14 Sum =  1.99987792969
13 Sum =  1.99975585938
12 Sum =  1.99951171875
11 Sum =  1.9990234375
10 Sum =  1.998046875
9 Sum =  1.99609375
8 Sum =  1.9921875
7 Sum =  1.984375
6 Sum =  1.96875
5 Sum =  1.9375
4 Sum =  1.875
3 Sum =  1.75
2 Sum =  1.5
1 Sum =  1.0
0 Sum =  0.0


### While loops 

We often use while loops for iterative methods, such as fixed-point iterations. These are typically used when we are unsure exactly how many iterations a process should take.

```
while condition:   #this condition is true
    do something cool
    update condition, or use break or continue for loop control
#no indent as at end of loop
```
If the the ``condition`` never becomes false, then this will result in an infinite loop, so be careful. It is therefore fairly common practice to include some type of counter tracking the number of iterations that makes the condition false if a maximum number of conditions has been reached.

You can also exit from any for loop by using ``break`` to exit the innermost loop, and ``continue`` to continue to the next iteration of this loop

Let's look at an example where we are trying to iterate a logistic equation $x_{n+1}=a*x_n*(1-x_n)$ until we arrive at a fixed point:

In [5]:
import math as m
#from math import fabs  #absolute value function
a = 2.0
xnew = .1
tol = 1E-8
doit = True  #boolean True and False 
while doit:
    xold = xnew
    xnew *= a * (1-xnew)
    if m.fabs(xnew-xold) > tol:
        print 'Iterating, X = ', xnew
        #continue  #play it again, Sam
    else:
        break
    print 'This is skipped if the continue command is not commented out above.'
print "Fixed Point=",xnew

Iterating, X =  0.18
This is skipped if the continue command is not commented out above.
Iterating, X =  0.2952
This is skipped if the continue command is not commented out above.
Iterating, X =  0.41611392
This is skipped if the continue command is not commented out above.
Iterating, X =  0.485926251164
This is skipped if the continue command is not commented out above.
Iterating, X =  0.499603859187
This is skipped if the continue command is not commented out above.
Iterating, X =  0.499999686145
This is skipped if the continue command is not commented out above.
Iterating, X =  0.5
This is skipped if the continue command is not commented out above.
Fixed Point= 0.5


# Exercise: Simple Finite-Difference Discretization of a PDE

Troy to-do: discretize heat equation using explicit time stepping. Describe process with some pictures and basic Centered Finite Difference scheme along with Neumann BC. Setup a "fill-in-the-blank" code snippets with a function that gets an index of an array and determines what the value of the stiffness matrix should be through if-elif-else conditional. Then nested-loop through the indices. This is intended to be functional and for pedagogical purposes only, not efficient. Then, use a while loop to walk through the time steps where students can change the time-step but it is truncated at the final time if the time-step does not evenly divide into $t_f$. Plot vs the exact solution from previous lecture.