# CCM Tutorial, Lecture II

## Conditionals \& Comparisons in Python
    
### Conditionals in Python    
1. No Case statement
2. if/elif/else SYNTAX
```
if condition:
    #do stuff
elif condition:
    #do stuff
else:
    #do stuff
```       
All parts of the conditional are indented.
       
### Comparison operators  (*LET a=3, b=5*)
==:	If the values of two operands are equal, then the condition becomes true.	*(a == b) is not true.*

!=:	If values of two operands are not equal, then condition becomes true.

<>:	If values of two operands are not equal, then condition becomes true.

 ">":	If the value of left operand is greater than the value of right operand, then condition becomes true.	*(a > b) is not true.*

"<": If the value of left operand is less than the value of right operand, then condition becomes true.	*(a < b) is true.*

">=":	If the value of left operand is greater than or equal to the value of right operand, then condition becomes true.	*(a >= b) is not true.*

"<=":	If the value of left operand is less than or equal to the value of right operand, then condition becomes true.	*(a <= b) is true.*

We can us **and** and **or** to combine sets of comparison operators and **not** to negate a statement. 

Example: 
```
if x >= 0 and not(x==2 or x==3):
            f=np.pow(x,.5)/((x-2.0)*(x-3.0)
         elseif x<0:
             print 'Square root of negative number'
            f=np.nan
         elseif x=2.0:
             print 'Division by zero with different limits'
             f=np.nan
```
Let's do an example for computing the finite element chapeaux function corresponding to node $x=0$ and meshsize= 2.

In [ ]:
# if x > 1 or x < -1 f(x)=0
# elif x<= 0 f(x)=1+x
# else f(x)=1-x

x=-.25
if x> 1 or x< -1:
    f=0.0
elif x<=0:
    f=1.0+x
else: 
    f=1.0-x
print f




## Looping in Python

### For loops

**Syntax** 
```
for iterator in list:
    #indent for the loop
    #do cool stuff in the loop
#noindent to close the loop'
```
The list can be strings, for example:
```
for string in ('Alpha','Romeo','Sailor','Foxtrot'):
    #string takes on values 'Alpha', 'Romeo', etc. in order.
    print string
```
    

You will commonly use the **xrange** command to build lists of numbers to iterate on.
This is better than **range** for long sets of numbers or if you break the loop earlier.

**SYNTAX** 
```
xrange(stop)  #assumes start=0
xrange(start, stop[, step])
```

Note that it **DOES NOT** execute the stop value.

Let's  sum the first 20 terms of the geometric series corresponding to $2^{-x}$

In [5]:
sum=0
for n in xrange(20):   #identical so xrange(0,20) or xrange(0,20,1)
    sum+=2**(-n)
    print n,'Sum=',sum
for n in xrange(19,-1,-1): #you need the colon
    sum-=2**(-n)  #all the things at the level of the loop get one indent
    print n,'Sum=',sum #done with the loop variable

0 Sum= 1
1 Sum= 1.5
2 Sum= 1.75
3 Sum= 1.875
4 Sum= 1.9375
5 Sum= 1.96875
6 Sum= 1.984375
7 Sum= 1.9921875
8 Sum= 1.99609375
9 Sum= 1.998046875
10 Sum= 1.9990234375
11 Sum= 1.99951171875
12 Sum= 1.99975585938
13 Sum= 1.99987792969
14 Sum= 1.99993896484
15 Sum= 1.99996948242
16 Sum= 1.99998474121
17 Sum= 1.99999237061
18 Sum= 1.9999961853
19 Sum= 1.99999809265
19 Sum= 1.9999961853
18 Sum= 1.99999237061
17 Sum= 1.99998474121
16 Sum= 1.99996948242
15 Sum= 1.99993896484
14 Sum= 1.99987792969
13 Sum= 1.99975585938
12 Sum= 1.99951171875
11 Sum= 1.9990234375
10 Sum= 1.998046875
9 Sum= 1.99609375
8 Sum= 1.9921875
7 Sum= 1.984375
6 Sum= 1.96875
5 Sum= 1.9375
4 Sum= 1.875
3 Sum= 1.75
2 Sum= 1.5
1 Sum= 1.0
0 Sum= 0.0


## Looping in Python: While loops 

We often use while loops for iterative methods, such as fixed-point iterations. 
```
error=float(1)
tol=1E-8
while condition:   #this condition is true
    do something cool
    update condition, or use break or continue for loop control
#no indent as at end of loop
```
If the *err > tol* never becomes invalid this will result in an infinite loop, so be careful.

You can also exit from any for loop by using **break** to exit the innermost loop, and **continue** to continue to the next iteration of this loop

Let's look at an example where we are trying to iterate a logistic equation $x_{n+1}=a*x*(1-x)$ until we arrive at a fixed point:

In [ ]:
import math as m
#from math import fabs  #absolute value function
a=2.0
xnew=.1
doit=True  #boolean True and False 
while doit:
    xold=xnew
    xnew*=a*(1-xnew)
    if m.fabs(xnew-xold) > 1E-8:
        print 'Iterating, X=',xnew
        continue  #play it again, Sam
    else:
        break
print "Fixed Point=",xnew

## **Functions in Python**  
```
def functionname( parameters ):
   "function_docstring"
   function_suite
   return [expression]
```
The quotes is where you put in a documentation string for your function.  It is entirely optional.

parameters are normally ordered **UNLESS** you supplement them with *keyword args* in the function call.  For example:

In [6]:
def myfun(x,y):
    return x+y

print myfun(2,3)
print myfun(2.0,3.0)
print myfun(y=2.0,x=3.0)
print myfun(x=3,y=2.0)
print myfun('silly ','test')    

5
5.0
5.0
5.0
silly test


Obviously Python does not use type-checking for functions, but it allows useful types of polymorphism.

Python also allows to set defaults within the parameter list of a function call.  Let's tweak myfun a little.

Defaults need to **come after** functions parameters with non-default values.

In [17]:
def myfun2(x=1,y=2):
    return x/y

print myfun2()
print myfun2(1.0)
print myfun2(y=3)

0
0.5
0


Can I pass a function to another function: **YES!**

Example: *secant method* for solving $f(x)=0$.

In [14]:
import numpy as np
def secant(function,guess=np.array([1.0,2.0]),tolerance=1E-8,max_iter=10):
    from math import fabs
    iter=0
    while fabs(function(guess[1])) > tolerance and iter < max_iter:
        temp=guess[1]-function(guess[1])*(guess[1]-guess[0])/(function(guess[1])-function(guess[0])) #secant update
        guess=[guess[1],temp]  #update secant vector
        iter+=1 #update iteration count
        print 'Iteration', iter,':X=',guess[1] #output iteration, current root guess
    return guess[1]    

def myfunc(x):
    from math import sin
    return x-sin(x)

def functwo(x):
    from math import atan
    return x-1-atan(x)

root=secant(myfunc,np.array([-.5,-.75])) #slow convergence, multiple root
root2=secant(functwo,np.array([-1.0,1])) 

Iteration 1 :X= -0.392363212133
Iteration 2 :X= -0.331154383525
Iteration 3 :X= -0.238361762951
Iteration 4 :X= -0.182944883534
Iteration 5 :X= -0.137116837399
Iteration 6 :X= -0.103748384711
Iteration 7 :X= -0.0782288331826
Iteration 8 :X= -0.0590710983367
Iteration 9 :X= -0.0445829062275
Iteration 10 :X= -0.0336556832203
Iteration 1 :X= 4.65979236633
Iteration 2 :X= 1.93149385608
Iteration 3 :X= 2.1105411114
Iteration 4 :X= 2.13267610613
Iteration 5 :X= 2.13226696793
Iteration 6 :X= 2.13226772525


### Python is pass by reference OR pass by value

####  *Pass by reference*
This means python passes the reference to the variable, not just the value.  This can cause some different behavior.  Classes, numpy arrays, etc. are passed by reference

#### *Pass by value* 
This means python passes the value and creates a new copy within the function. strings, floats, and ints are passed by value (*they are immutable data types*)

Python variables created within a function also have local *scope*.

In [9]:
import numpy as np
def tester(var):
    var*=2      #if var is mutable, replaces in place(pass-by-reference)
    print 'var=',var
    a=3
    print 'tester  changed a to',a #I can access a global variable here, and change it locally.
    return

a=2
print 'before tester, a=',a
tester(a)
print 'after tester, a=',a
A=np.ones([2,2])
print 'before tester, array A=',A
tester(A)
print 'after tester, array A=',A
tester2(A)
print 'after tester 2, array A='


before tester, a= 2
var= 4
tester  changed a to 3
after tester, a= 2
before tester, array A= [[ 1.  1.]
 [ 1.  1.]]
var= [[ 2.  2.]
 [ 2.  2.]]
tester  changed a to 3
after tester, array A= [[ 2.  2.]
 [ 2.  2.]]
a= [[ 4.  4.]
 [ 4.  4.]]
[[ 2.  2.]
 [ 2.  2.]]


What if I want to do local work to a *mutable* data type(i.e. a numpy array) but not have the change reflected back 
after function exit?  

The answer is to not use *in place* operators like +=, \*=, etc.  var=var+2 creates a local copy of var and adds 2 to every entry.

In [12]:
def tester2(var):
    var=var*2    #if mutable, creates local copy of var.
    print 'in function, input=',var
    return 

A=np.eye(3) # creates 3x3 array with a_ii = 1, 0 otherwise.
print 'before tester2, A=',A
tester2(A)
print 'after tester2, A=',A

before tester2, A= [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
in function, input= [[ 2.  0.  0.]
 [ 0.  2.  0.]
 [ 0.  0.  2.]]
after tester2, A= [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
